
services:
  mysqldb:
    image: mariadb:11
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MARIADB_DATABASE=${MYSQLDB_DATABASE}
      - MARIADB_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
  app:
    depends_on:
      - mysqldb
    restart: on-failure
    image: bookshop-app
    build: .
    env_file: ./.env
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
      - ${DEBUG_PORT}:${DEBUG_PORT}

    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}",
        "spring.datasource.username": "${MYSQLDB_USER}",
        "spring.datasource.password": "${MYSQLDB_ROOT_PASSWORD}",
        "jwt.expiration": "${JWT_EXPIRATION}",
        "jwt.secret": "${JWT_SECRET}",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
        "spring.datasource.driver-class-name" : "com.mysql.cj.jdbc.Driver"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:${DEBUG_PORT}"