version: "3.8"

services:
  mysqldb:
    image: mysql:8.2.0
    restart: unless-stopped
    env_file: .env.properties
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}

#    healthcheck:
#      test: [ "m_isready -U mysql" ]
#      interval: 30s
#      timeout: 30s
#      retries: 3
  app:
    depends_on:
      - mysqldb
    restart: on-failure
    image: bookshop
    build: .
    env_file: .env.properties
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
      - ${DEBUG_PORT}:${DEBUG_PORT}
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:${MYSQL_DOCKER_PORT}/${MYSQL_DATABASE}",
        "spring.datasource.username": "${MYSQL_USER}",
        "spring.datasource.password": "${MYSQL_ROOT_PASSWORD}",
        "jwt.expiration": "${JWT_EXPIRATION}",
        "jwt.secret": "${JWT_SECRET}"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:${DEBUG_PORT}"